### ISSUE TITLE
PNG file support

### ISSUE THREAD

**Issue by zuhito** [IBM/MAX-Human-Pose-Estimator#12]
Human-Pose-Estimator has [the same problem as Facial Age Estimator](https://github.com/IBM/MAX-Facial-Age-Estimator/issues/13). Image Caption Generator, Facial Recognizer, and Object Detector support both JPG and PNG files. On the other hand, Human-Pose-Estimator and Facial Age Estimator can handle only a JPG file. It will be easy for developers to switch MAX container which is related to image recognition if all containers support both JPG and PNG files.

**Comment by MLnick** [comment]
I think this is best handled at the level of `MAX-Framework` to provide common utility functions that can be re-used by all relevant models. See https://github.com/IBM/MAX-Framework/issues/8
