### ISSUE TITLE
JPG/PNG images containing alpha channel information break /model/predict

### ISSUE THREAD

**Issue by ptitzler** [IBM/MAX-Human-Pose-Estimator#13]
Receiving this input

![camera](https://user-images.githubusercontent.com/13068832/53530868-333b0980-3aa6-11e9-8780-0bb378024379.jpg)

`/mode/predict` returns HTTP code 500 and the console output contains a stack trace entry 
similar to the following: `ValueError: Cannot feed value of shape (1, 615, 461, 4) for Tensor 'pnet/input:0', which has shape '(?, ?, ?, 3)'`

**Comment by MLnick** [comment]
Fixed in #14
