### ISSUE TITLE
No module named '_pafprocess' you need to build c++ library for pafprocess.

### ISSUE THREAD

**Issue by yahyanik** [IBM/MAX-Human-Pose-Estimator#31]
I am complimenting this human pose estimation on my local Raspberry PI. Since the docker image and the base docker image are both made for x86 processors, I cannot use them and so I am just preparing the environment myself. After installing all requirements and other basic tools, I got the error: "No module named '_pafprocess'
you need to build c++ library for pafprocess.
See: https://github.com/ildoonet/tf-pose-estimation/tree/master/tf_pose/pafprocess"
Based on what I read it is a low-level tf library. Is there a way to solve this issue and run the program?

**Comment by feihugis** [comment]
@yahyanik If you could not use the docker image, you need to manually build the code under [core/tf_pose/pafprocess](https://github.com/IBM/MAX-Human-Pose-Estimator/tree/master/core/tf_pose/pafprocess) as the Dockerfile does [here](https://github.com/IBM/MAX-Human-Pose-Estimator/blob/master/Dockerfile#L37):
```bash
$ cd core/tf_pose/pafprocess/
$ swig -python -c++ pafprocess.i 
$ python setup.py build_ext --inplace
```

**Comment by yahyanik** [comment]
wow, totally missed it. thank you for the response. I made it work thanks to you.

**Comment by feihugis** [comment]
Great. I will close this issue.

**Comment by jagadeesh1414** [comment]
$ swig -python -c++ pafprocess.i 
$ python setup.py build_ext --inplace
how to use these two comands in colab
![Screenshot (110)](https://user-images.githubusercontent.com/67110744/129900711-498f2994-11c0-4815-8214-8044a2f0ec0f.png)

**Comment by talha-khalid-qureshi** [comment]
@jagadeesh1414 

> $ swig -python -c++ pafprocess.i
> $ python setup.py build_ext --inplace
> how to use these two comands in colab
> ![Screenshot (110)](https://user-images.githubusercontent.com/67110744/129900711-498f2994-11c0-4815-8214-8044a2f0ec0f.png)

please try
!apt-get install swig 
!swig -python -c++ pafprocess.i

**Comment by kqsgdka** [comment]
![image](https://user-images.githubusercontent.com/55948975/135080533-819dc897-b63e-495e-a9a8-aab2cbedb1ac.png)

**Comment by seongwookthegod** [comment]
> ![image](https://user-images.githubusercontent.com/55948975/135080533-819dc897-b63e-495e-a9a8-aab2cbedb1ac.png)

I faced the same problem as you. (Unable to fine file 'pafprocess.i' Did you solve it?
