### ISSUE TITLE
Docker image for aarch64 ?

### ISSUE THREAD

**Issue by FlorianRuen** [IBM/MAX-Human-Pose-Estimator#33]
Hi,

I'm using the Human-pose-estimator for my tests (building image locally), and for some reasons, I need to change my machine to a Jetson Nano.

The main problem is that the DockerFile is for x86 machines and Jetson nano running on aarch64. Do you have any image for this architecture, to build this image on my Jetson Nano ?

Thanks a lot,

Regards,
Florian

**Comment by bdwyer2** [comment]
Hi Florian,

You can try changing the base image to `codait/max-base:arm-arm32v7-latest`

**Comment by ptitzler** [comment]
To be specific change line https://github.com/IBM/MAX-Human-Pose-Estimator/blob/master/Dockerfile#L17  from 

```
FROM codait/max-base:v1.1.3
```

to 
```
FROM codait/max-base:arm-arm32v7-latest
```

**Comment by FlorianRuen** [comment]
@bdwyer2 @ptitzler Thanks for your help to find a solution. I will try this in few days, for the moment I found alternative without Docker to run the script on my Jetson nano.

Just another question: do you know if it's possible to choose the model ? (I see on Openpose, on which is based this code, that there is a light model, faster)

Thanks again

**Comment by ptitzler** [comment]
Unfortunately not at this time (we do for other models). However, we periodically review models/implementations and refresh our images should something "better" become available.

**Comment by FlorianRuen** [comment]
@ptitzler I will try on my own to make something, because I find the analysis time "is long" on GPU (Tesla M60 8GB). It it take around 1-1.5 seconds for just one image. Do you have others statistics of analysis time on your side ?
