### ISSUE TITLE
Pre-built image not accessible

### ISSUE THREAD

**Issue by dzek69** [IBM/MAX-Human-Pose-Estimator#52]
In the readme we read:

> To run the docker image, which automatically starts the model serving API, run:
```
$ docker run -it -p 5000:5000 quay.io/codait/max-human-pose-estimator
```
> This will pull a pre-built image from the Quay.io container registry (or use an existing image if already cached locally) and run it. If you'd rather checkout and build the model locally you can follow the run locally steps below.

But trying this command ends with:
```
docker run -it -p 5000:5000 max-human-pose-estimator
Unable to find image 'max-human-pose-estimator:latest' locally
docker: Error response from daemon: pull access denied for max-human-pose-estimator, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

After registering an account and successfully using `docker login` the same message appears.

**Comment by bdwyer2** [comment]
Hi @dzek69,

I think you are following the instructions for running an image you built yourself locally.

Does this command work for you?

`docker run -it -p 5000:5000 quay.io/codait/max-human-pose-estimator`

**Comment by xuhdev** [comment]
@dzek69 Your command missed `quay.io/codait/` in the image name

**Comment by dzek69** [comment]
You are both right. Looks like I was in a rush and totally missed the fact I've copied wrong command 🤦🏻‍♂️  Sorry and thanks for your help.
